### ISSUE TITLE
Doc Error

### ISSUE THREAD

**Issue by yuanshanhshan** [rookie-ninja/rk-db#3]
https://github.com/rookie-ninja/rk-db/blob/master/mongodb/README.md

import mongo package is : github.com/rookie-ninja/rk-db/mongodb

**Comment by dongxuny** [comment]
@yuanshanhshan Hi

The error in docs was fixed. Furthermore, docs for mongoDB was added in official site:https://docs.rkdev.info/docs/rk-boot/getting-started/database/mongodb/

**Comment by yuanshanhshan** [comment]
Thank U Very much


dongxuny ***@***.***> 于2022年6月17日周五 18:26写道：

**Comment by dongxuny** [comment]
Please reopen this issue if there are any problems occur. I am going to close this issue
